spring.application.name=PersonalFinance

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA & Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SHOW_SQL}

# JWT
venn.jwt.base64-secret=${JWT_SECRET}
venn.jwt.access-token-validity-in-seconds=${JWT_ACCESS_EXPIRE}
venn.jwt.refresh-token-validity-in-seconds=${JWT_REFRESH_EXPIRE}

# config pageable 
spring.data.web.pageable.page-parameter=currentPage
spring.data.web.pageable.size-parameter=pageSize
spring.data.web.pageable.one-indexed-parameters=true


###
#config email with Gmail
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}

spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
###
#

#config redis 
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# rabbitmq
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

#base path
vennhuu.upload-file.base-uri=file:///E:/VTIT/PersonalFinance/upload/
# vennhuu.upload-file.base-uri=file:///app/uploads/
